version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "brand-container"
          ContainerPort: 8082
Hooks:
  - BeforeInstall:
      - location: "arn:aws:lambda:ap-northeast-2:026090537156:function:brandAPITestFunction"
        timeout: 300
  - AfterInstall:
      - location: "arn:aws:lambda:ap-northeast-2:026090537156:function:brandAPITestFunction"
        timeout: 300
  - AfterAllowTestTraffic:
      - location: "arn:aws:lambda:ap-northeast-2:026090537156:function:brandAPITestFunction"
        timeout: 300
  - BeforeAllowTraffic:
      - location: "arn:aws:lambda:ap-northeast-2:026090537156:function:brandAPITestFunction"
        timeout: 300
  - AfterAllowTraffic:
      - location: "arn:aws:lambda:ap-northeast-2:026090537156:function:brandAPITestFunction"
        timeout: 300